### ISSUE TITLE
cmake release problem during using qt6

### ISSUE THREAD

**Issue by somalcy** [CerebusOSS/CereLink#130]
Hi, 

We set the `prefix_path` to the qt6 installed path in cmakefile, because the system can not find qt6 library, 

> set(CMAKE_PREFIX_PATH "/opt/Qt6/6.1.2/gcc_64")

but there still exist some problems when we operate the following code

> cmake --build build --config Release

it tell us about that

> /usr/bin/ld: CMakeFiles/testcbsdk.dir/cbhwlib/cbhwlib.cpp.o: undefined reference to symbol 'shm_open@@GLIBC_2.2.5'

It seems the new package used boost environment, but the given tutorial not tell the user how to deploy it.

Thanks for all the support!
Soma

**Comment by cboulay** [comment]
What version of Linux are you on?

You shouldn't have to edit CMakeLists.txt yourself. You can pass the CMAKE_PREFIX_PATH as an argument:
`cmake --build build --config Release -DCMAKE_PREFIX_PATH="/opt/Qt6/6.1.2/gcc_64"`

I don't think we're using boost anywhere. Rather, I think the problem is that `testcbsdk` isn't linking all of its dependencies. I can fix this in my current edits. In the meantime, try to build with `-DBUILD_TEST=OFF`

**Comment by somalcy** [comment]
Thanks for your reply. My linux version is 20.04 and we tried your advise. It can complete the cmake part
